"""This module defines the ManifestQuery class, which provides methods to query a Manifest object.
The ManifestQuery class allows users to retrieve artefacts, metrics, and input data from a manifest."
The aim of this class is to serve as an interface to access and filter the components of a manifest in a structured way,
enabling users to easily extract relevant information based on specific criteria."""

from typing import Optional

from DSL4Pipelines.src.metamodel.manifests.manifests import Manifest
from DSL4Pipelines.src.metamodel.artefacts.artefacts import Artefact
from DSL4Pipelines.src.metamodel.artefacts.metrics import Metric
from DSL4Pipelines.src.metamodel.relations.relations import Relationship
from DSL4Pipelines.src.metamodel.pipelines.workflow import Task
from DSL4Pipelines.src.metamodel.core.structure import Element


class ManifestQuery:
    """ManifestQuery provides methods to query a Manifest object,
    allowing users to retrieve artefacts, metrics, and input data
    based on specific criteria.
    It serves as an interface to access and filter the components of a manifest in a structured way."""

    def __init__(self, manifest: Manifest):
        self.manifest = manifest

    def get_artifacts(self, type=None) -> list[Artefact]:
        """return a list of all artefacts of the manifest, optionally filtered by type."""
        allArtefacts = self.manifest.artefacts
        return [a for a in allArtefacts if not type or a.type == type]

    def get_metrics(self, kind=None, category=None) -> list[Metric]:
        """return a list of all metrics of the manifest, optionally filtered by kind and/or category.
        example: get_metrics(kind="accuracy") will return all metrics of kind accuracy", regardless of their category.
        example: get_metrics(category="PERFORMANCE") will return all metrics of category "PERFORMANCE", regardless of their kind.
        example: get_metrics(kind="accuracy", category="PERFORMANCE") will return all metrics of kind "accuracy" and category "PERFORMANCE"."""
        metrics = self.manifest.get_metrics()
        return [
            m
            for m in metrics
            if (not kind or m.kind == kind) and (not category or m.category == category)
        ]

    def get_input_relations(self, element: Task) -> list[Relationship]:
        """return a list of all relations of the manifest
        where the "to" element is the task specified in parameter"""
        relations = [r for r in self.manifest.relations if element in r.to_]
        return relations

    def get_input_artefacts(self, element: Optional[Task] = None) -> list[Artefact]:
        """return the list of all artefacts that are used as input by an element of the manifest, optionally filtered by this element.
        i.e. if a task is specified, return all artefacts that are used as input by this task (from) and to is the task specified in parameter.
        if no task is specified, return all artefacts that are used as input (from) but are never used as to.
        """
        if element is not None:
            artefacts = [
                r.from_
                for r in self.manifest.relations
                if element in r.to_ and isinstance(r.from_, Artefact)
            ]
            return artefacts
        else:
            # we get all artefacts that are used as input (from) in any relation of the manifest
            # we filter the relations to keep only those where the "from" element is an artefact, and we extract these artefacts
            artefacts = [
                r.from_
                for r in self.manifest.relations
                if isinstance(r.from_, Artefact)
            ]
            # we filter the artefacts to keep only those that are not used as "to" in any relation of type "input"
            filtered_artefacts = [
                a
                for a in artefacts
                if not any(a in r.to_ for r in self.manifest.relations)
            ]
            return filtered_artefacts

    def get_input_data(self, task=None):
        """return a list of all input data of the manifest, optionally filtered by task."""
        # A input data is an artefact DATA that is en relation with a task by a relation of type "input"""
        # If no task is specified,
        # return all input data of the manifest,
        # i.e. Data that are not generated by any task of the manifest
        # but are used as input by at least one task."""


# =====================================================================
# ---Test bloc and usage example---
# =====================================================================
if __name__ == "__main__":
    pass
